--- 
- 
  name: "Perform an update for all packages..."
  apt: update_cache=yes
  sudo: yes
- 
  name: "Perform an upgrade for all packages..."
  apt: upgrade=dist
  sudo: yes
-
  name: "Install Ruby via repository..."
  apt: name=ruby-full state=present
  sudo: yes
- 
  name: "Install dependances for PostgreSQL"
  apt: "name={{ item }} state=present"
  with_items:
  - python-psycopg2
  - libpq5
  - libpq-dev
  - git
  - gcc
  sudo: yes
-
  name: "Install PostgreSQL..."
  apt: "name={{ item }} state=present"
  with_items:
  - postgresql-9.4
  - postgresql-client-9.4
  sudo: yes
-
 name: "Install gem bundler..."
 gem: name=bundle state=latest
 sudo: yes
-
 name: "Create a PostgreSQL user and assign the user to the database created..."
 postgresql_user: db=WeddingApp name=twapp encrypted=true password=md5635848396f0b0ebcd06af458e935e406 priv=ALL 
 sudo: yes 
 sudo_user: postgres
-
 name: "Create the database for the app.."
 postgresql_db: name=WeddingApp login_user=postgres owner=twapp
 sudo: yes
 sudo_user: postgres 

